### ISSUE TITLE
Question about using SAM in the WEB

### ISSUE THREAD

**Issue by Futyn-Maker** [discordier/sam#18]
Hello!

I'd like to use the SAM in one WEB-game, so I have question. Did I understand correctly that I can use samjs.js-file as a standalone script? Do I need any other scripts for working SAM in browser? I've experimented in Chrome, TTS is working with this one file, but maybe I don't know something...

And one another question, how I can enable the phonetics mode?

Thanks

**Comment by discordier** [comment]
> I'd like to use the SAM in one WEB-game

See the license remarks, SAM is reverse engineered "abandonware". There might be legal implications when using it commercially.

> Did I understand correctly that I can use samjs.js-file as a standalone script?

Yes of course, have a look at the demos.

> Do I need any other scripts for working SAM in browser? I've experimented in Chrome, TTS is working with this one file, but maybe I don't know something...

No, that is all.

> And one another question, how I can enable the phonetics mode?

Have a look at the guess a number demo where only phonetics are defined [Link](https://github.com/discordier/sam/blob/4fdb4207dd85b3b5556bcfa0ee319e2f9f75727f/src/guessnum.es6#L3) and used.

**Comment by Futyn-Maker** [comment]
Thanks. I amn't going to use it comercially.
