### ISSUE TITLE
update required librarys to include libsdl1.2-dev in the compile section

### ISSUE THREAD

**Issue by samiscool51** [discordier/sam#22]
took me about 15 mins before i finally figured out that libsdl1.2-dev was the package required to compile the code and get it to work.
even if this doesn't get fixed those who are gonna do this will atleast know what they are missing instead of getting confused.

**Comment by discordier** [comment]
I assume you are talking about the C source portion. This is not needed for the Javascript compilation at all and included only for reference.

I should get rid of the sub repository I guess to better point this out.

**Comment by samiscool51** [comment]
> I should get rid of the sub repository I guess to better point this out.

don't get rid of it! it's one of those things that should never be taken down for preservation reasons!

**Comment by discordier** [comment]
you are aware that it is a sub repository to the `c-src` branch, which exists solely for preservation reasons.

However, it is not in use at all in the js src and therefore the sub module can be removed IMO (the branch will remain of course).
