### ISSUE TITLE
Rebuild to NPM without loads of console.log

### ISSUE THREAD

**Issue by g1xb17** [discordier/sam#25]
It would be really awesome if a simple rebuild of the package could be done where the build command is ran without development flags so that this is actually usable in a server application. If I want to use this I basically have to take the output, and post it into my own private repo and remove `PrintOutput` function, and other logging nightmares so its usable. Luckily the dist is pretty small. I won't explain how you can use this in a server, just know that the other thing is pretty annoying for logging.

**Comment by tyomitch** [comment]
@g1xb17 @dj-foxxy this is already a build option: the minified JS files are built without development flags, and they don't produce any output to the console.

@discordier I suppose that for the sake of NPM users, package.json should have
```
  "main": "dist/samjs.min.js",
  "module": "dist/samjs.esm.min.js",
```
