### ISSUE TITLE
How i download the audio?

### ISSUE THREAD

**Issue by arandombambi** [discordier/sam#34]
i dont know how to download audio.

**Comment by discordier** [comment]
You have to generate the audio (as in the demo in `index.html`) and instead of `sam.speak(this.textfield.value);` call `sam.download(this.textfield.value);`.

Hope this helps

**Comment by NoteEveryFriday** [comment]
> You have to generate the audio (as in the demo in `index.html`) and instead of `sam.speak(this.textfield.value);` call `sam.download(this.textfield.value);`.
> 
> Hope this helps

VM69:1 Uncaught ReferenceError: sam is not defined
    at <anonymous>:1:1

**Comment by discordier** [comment]
> what do you mean as in generate? i got into index.html but i don't see anything :(

I wonder how this may be... the code is there: https://github.com/discordier/sam/blob/e037db2845741457d72e0d862f901b42b8db4f5f/index.html#L69
