### ISSUE TITLE
Best way to call this from C++ code?

### ISSUE THREAD

**Issue by Khodyn** [discordier/sam#35]
The original C version of SAM is pretty buggy - this one seems to be far better maintained, but it's in JavaScript. Any idea how I can easily embed this in a C++ (MSVC) program?

**Comment by RedFoxIV** [comment]
@Khodyn 
please describe what you've done to get it working
i've been trying to get *anything* that could run JS from cpp to work for the last few days _and i swear v8 wants me to sacrifice a lamb to compile it_
