### ISSUE TITLE
Didn't work

### ISSUE THREAD

**Issue by User123421** [discordier/sam#38]
I copied the code, yet it says: "[error] Line 1: Uncaught SyntaxError: Unexpected identifier 'add'". 
Is there something missing or this code isn't for JavaScript?

**Comment by discordier** [comment]
I have no clue which code you copied and can therefore not be of much help.

However, have a look in the [gh-pages](https://github.com/discordier/sam/tree/gh-pages) branch as there are all examples included.

Aside from that, the master branch contains the sources in addition to the compiled scripts which get uploaded to npm.
