### ISSUE TITLE
SyntaxError: Cannot use import statement outside a module

### ISSUE THREAD

**Issue by egor835** [discordier/sam#40]
Import doesn't work.
![Screenshot_20230122-174024_Termux](https://user-images.githubusercontent.com/90187830/213921874-7b656a09-5a80-48fc-809c-9c78dd5bc0e1.png)
![Screenshot_20230122-174154_Termux](https://user-images.githubusercontent.com/90187830/213921876-0b3c8f8d-d2f5-4613-adbd-687b77ee5a34.png)
![Screenshot_20230122-174002_Termux](https://user-images.githubusercontent.com/90187830/213921877-57037752-95a0-458e-96ae-560b94ba168e.png)
Help plz. I'm a complete zero in js.

**Comment by egor835** [comment]
I tried it on mac os, same crap.
![Screenshot 2023-01-22 at 17 56 14](https://user-images.githubusercontent.com/90187830/213932892-d6397ff0-91fd-4a67-bb71-1ef82fdf7b21.png)

**Comment by discordier** [comment]
First of all, sam is targeted against browser usage, haven't tried it in node or deno yet.

Maybe we need to include `"type": "module"` in our `package.json` and it works.

**Comment by LiveRoman228** [comment]
с хуяли ты это мне отправляешь. я не разработчик этой хуйни.

пн, 23 янв. 2023 г., 15:00 Christian Schiffler ***@***.***>:

**Comment by egor835** [comment]
> с хуяли ты это мне отправляешь.

каво? я issue открыл, тебе не отправлял ничё

**Comment by discordier** [comment]
> с хуяли ты это мне отправляешь. я не разработчик этой хуйни. 

I don't see your problem... I am commenting on an issue in **MY repository** to which **YOU** apparently **subscribed** to.
Yet YOU are insulting ME for sending a mail which you subscribed to. 
Pretty shows the current Russian mood of blaming others for their own actions.

Unsubscribe from my repository and you won't get mails and waste my and others time with useless conversation.

And for the record - get your men out of Ukraine!
