### ISSUE TITLE
Allowed USAGE 

### ISSUE THREAD

**Issue by brendenderp** [discordier/sam#49]
Hard for me to verify the legitimacy of this  but it appears at at some point someone reached out to Joseph Katz regarding either this project or a similar one. I can't find contact info for Joseph but it appears he is willing to grant individuals permission to use the software for non-commercial use

.  I've been doing heavy research into tracking him down as I wanted to use it in something commercial but I'm not sure what the answer would be on that. 

In any case it might be worth looking into.

https://nvda.groups.io/g/nvda/topic/softvoice_information_request/5170758

**Comment by discordier** [comment]
Hello and thanks for letting me know.

Apparently they inquried about "softVoice tts from back in windows98 and windows xp time period" which came way after S.A.M.

S.A.M. was released 1982 while the "new" TTS by softvoice came at earliest in Jun 1998 (release year Windows 98).

Therefore, they are not the same.

I'd love if Mr. Katz (or anyone else at Softvoice Inc.) would chime in and give official grant to release this first gen TTS under MIT or something similar.

**Comment by brendenderp** [comment]
Dang. That's good to hear atleast as it doesn't rule out aproval for general use of the product. When I was digging around for his contact info all I could find was a phone number which I didn't dare call. Would love for this to be under the MIT license especially with how well it runs in the browser.  Dectalk is a good alternative  but seems much slower. 

Thank you for your response! I'll close the issue.
